server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/savey
    driver: org.postgresql.Driver
    username: postgres
    password: 1
    platform: postgres
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update